#!/usr/bin/env bash
# =============================================================================
# build.sh - macOS build for this repo.
# =============================================================================
#
# Direct clang invocation, no CMake, no Xcode project. Mirrors the
# Linux DRM / X11 build scripts: compile each source into a single
# binary, stage assets next to it. platform_macos.m is an
# Objective-C TU; clang handles .m vs .c automatically from the
# file extension. Every other source is plain C.
#
# OUTPUT: $SCRIPT_DIR/guidemo   (Mach-O, linked against system
# frameworks: Cocoa, OpenGL, CoreVideo, Foundation)
#
# USAGE
#   ./build.sh                    # DEFAULT: build + run
#   ./build.sh build              # build only
#   ./build.sh run                # run only
#   ./build.sh clean              # wipe build outputs
#
# DEPENDENCIES
#   - macOS 10.12+ (older might work but untested; NSOpenGLView
#     has been around forever, NSOpenGLProfileVersion4_1Core since
#     10.9)
#   - Apple's Command Line Tools (ships clang + frameworks):
#         xcode-select --install
#
# Works on both Intel (x86_64) and Apple Silicon (arm64). The host
# arch is picked automatically.
#

set -euo pipefail

APPNAME=${APPNAME:-guidemo}
TARGET=${1:-run}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

BUILD_DIR="$SCRIPT_DIR/build"
BIN_OUT="$SCRIPT_DIR/$APPNAME"

info()  { printf '\033[36m[build]\033[0m %s\n' "$*"; }
ok()    { printf '\033[32m[build]\033[0m %s\n' "$*"; }
err()   { printf '\033[31m[build]\033[0m %s\n' "$*" >&2; }
fatal() { err "$*"; exit 1; }

CC=${CC:-$(command -v clang)}
[[ -x "$CC" ]] || fatal "clang not found. Run: xcode-select --install"

# -----------------------------------------------------------------------------
# Sources. One .m + everything else as .c. clang treats .m as
# Objective-C automatically; no per-file -x flag needed.
# -----------------------------------------------------------------------------

SOURCES=(
    "$ROOT/gui/src/scene.c"
    "$ROOT/gui/src/platforms/macos/fs_macos.c"
    "$ROOT/gui/src/font.c"
    "$ROOT/gui/src/scroll.c"
    "$ROOT/gui/src/animator.c"
    "$ROOT/gui/src/parser_xml.c"
    "$ROOT/gui/src/parser_style.c"
    "$ROOT/gui/src/widget_registry.c"
    "$ROOT/gui/src/widgets/widget_window.c"
    "$ROOT/gui/src/widgets/widget_column.c"
    "$ROOT/gui/src/widgets/widget_row.c"
    "$ROOT/gui/src/widgets/widget_button.c"
    "$ROOT/gui/src/widgets/widget_slider.c"
    "$ROOT/gui/src/widgets/widget_div.c"
    "$ROOT/gui/src/widgets/widget_text.c"
    "$ROOT/gui/src/widgets/widget_input.c"
    "$ROOT/gui/src/widgets/widget_checkbox.c"
    "$ROOT/gui/src/widgets/widget_radio.c"
    "$ROOT/gui/src/widgets/widget_select.c"
    "$ROOT/gui/src/widgets/widget_option.c"
    "$ROOT/gui/src/widgets/widget_image.c"
    "$ROOT/gui/src/widgets/widget_collection.c"
    "$ROOT/gui/src/widgets/widget_colorpicker.c"
    "$ROOT/gui/src/widgets/widget_popup.c"
    "$ROOT/gui/src/widgets/widget_textarea.c"
    "$ROOT/gui/src/widgets/widget_canvas.c"
    "$ROOT/gui/src/widgets/widget_keyboard.c"
    "$ROOT/gui/src/third_party/log.c"
    "$ROOT/gui/src/renderers/gles3_renderer.c"
    "$ROOT/gui/src/platforms/macos/platform_macos.m"
    "$ROOT/gui/src/clib/memory_manager.c"
    "$ROOT/gui/src/clib/stdlib.c"
    "$ROOT/gui/src/hot_reload.c"
    "$SCRIPT_DIR/main.c"
)

gen_defines() {
    mkdir -p "$BUILD_DIR"
    local defs="$BUILD_DIR/macos_build_defines.h"
    cat > "$defs" <<EOF
/* Auto-generated by build.sh -- do not edit. */
#ifndef MACOS_BUILD_DEFINES_H
#define MACOS_BUILD_DEFINES_H
#define APPNAME "$APPNAME"
#define DEMO_SOURCE_DIR "$SCRIPT_DIR/assets"
#define GUI_FONTS_SOURCE_DIR "$SCRIPT_DIR/assets/fonts"
#endif
EOF
}

stage_assets() {
    local dst="$SCRIPT_DIR/assets"
    mkdir -p "$dst"
    mkdir -p "$dst/fonts"
    mkdir -p "$dst/wallpapers"

    for f in "$ROOT/demo-windows"/*.ui "$ROOT/demo-windows"/*.style "$ROOT/demo-windows"/*.png "$ROOT/demo-windows"/*.jpg "$ROOT/demo-windows"/*.jpeg; do
        if [ -f "$f" ]; then
            bn=$(basename "$f")
            if printf '%s' "$bn" | LC_ALL=C grep -q '[^ -~]'; then continue; fi
            cp -u "$f" "$dst/"
        fi
    done

    if [ -d "$ROOT/demo-windows/wallpapers" ]; then
        for f in "$ROOT/demo-windows/wallpapers"/*.png "$ROOT/demo-windows/wallpapers"/*.jpg "$ROOT/demo-windows/wallpapers"/*.jpeg; do
            if [ -f "$f" ]; then
                bn=$(basename "$f")
                if printf '%s' "$bn" | LC_ALL=C grep -q '[^ -~]'; then continue; fi
                cp -u "$f" "$dst/wallpapers/"
            fi
        done
    fi

    if [ -d "$ROOT/gui/src/fonts" ]; then
        for f in "$ROOT/gui/src/fonts"/*.ttf; do
            if [ -f "$f" ]; then cp -u "$f" "$dst/fonts/"; fi
        done
    fi

    ok "staged assets -> $dst"
}

target_build() {
    gen_defines
    stage_assets

    local defs="$BUILD_DIR/macos_build_defines.h"

    local cflags=(
        -O2 -g
        -fvisibility=hidden
        -fobjc-arc
        -Wall -Wno-unused-function -Wno-deprecated-declarations
        -DGUI_TRACK_ALLOCATIONS
        -include "$defs"
        -I"$ROOT/gui/src"
    )

    local ldflags=(
        -framework Cocoa
        -framework OpenGL
        -framework CoreVideo
        -framework Foundation
        -lm -ldl -lpthread
    )

    info "compiling $APPNAME"
    "$CC" "${cflags[@]}" -o "$BIN_OUT" "${SOURCES[@]}" "${ldflags[@]}"
    ok "built $BIN_OUT"
    local size
    size=$(stat -f%z "$BIN_OUT" 2>/dev/null || echo '?')
    info "size: $size bytes"

    bundle_app
}

#
# Wrap the bare Mach-O into a minimal .app bundle so Finder treats
# it as a launchable application. Layout:
#
#   $APPNAME.app/
#     Contents/
#       Info.plist             metadata Cocoa needs to register the app
#       MacOS/$APPNAME         the binary (copied, not symlinked)
#       Resources/             assets/ staged here for runtime access
#
# Double-clicking the .app launches it via Finder; running from a
# terminal still works against the bare binary at $BIN_OUT.
#
bundle_app() {
    local app_dir="$SCRIPT_DIR/$APPNAME.app"
    local contents="$app_dir/Contents"
    local macos_dir="$contents/MacOS"
    local res_dir="$contents/Resources"

    mkdir -p "$macos_dir" "$res_dir"
    cp -f "$BIN_OUT" "$macos_dir/$APPNAME"

    cat > "$contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>          <string>$APPNAME</string>
    <key>CFBundleIdentifier</key>          <string>org.novyworkbench.$APPNAME</string>
    <key>CFBundleName</key>                <string>$APPNAME</string>
    <key>CFBundleDisplayName</key>         <string>$APPNAME</string>
    <key>CFBundleVersion</key>             <string>0.1.0</string>
    <key>CFBundleShortVersionString</key>  <string>0.1.0</string>
    <key>CFBundlePackageType</key>         <string>APPL</string>
    <key>CFBundleSignature</key>           <string>????</string>
    <key>LSMinimumSystemVersion</key>      <string>10.12</string>
    <key>NSHighResolutionCapable</key>     <true/>
    <key>NSPrincipalClass</key>            <string>NSApplication</string>
</dict>
</plist>
EOF

    #
    # Stage the asset tree inside the bundle's Resources dir as
    # well as keeping the loose copy at $SCRIPT_DIR/assets. The
    # binary in the bundle will read from its own ./Resources
    # path (same DEMO_SOURCE_DIR baked in -- works either way
    # since we keep both copies in sync), and the loose binary
    # uses the loose assets.
    #
    if [ -d "$SCRIPT_DIR/assets" ]; then
        rm -rf "$res_dir/assets"
        cp -R "$SCRIPT_DIR/assets" "$res_dir/assets"
    fi
    ok "wrapped $app_dir"
}

target_run() {
    target_build
    info "running $BIN_OUT"
    "$BIN_OUT"
}

target_clean() {
    for p in "$BUILD_DIR" "$BIN_OUT" "$SCRIPT_DIR/assets" "$SCRIPT_DIR/$APPNAME.app"; do
        if [[ -e "$p" ]]; then
            info "removing $p"
            rm -rf "$p"
        fi
    done
    ok 'clean done'
}

case "$TARGET" in
    run|'')   target_run ;;
    build)    target_build ;;
    clean)    target_clean ;;
    *)        err "Unknown target: $TARGET"; echo "Valid: run (default), build, clean"; exit 2 ;;
esac
