//
// demo-settings/main.c - a fake "Settings" app that sits alongside
// meek-shell as a regular Wayland client. Used to verify Phase 2 of
// the compositor/shell pipeline: this app connects to
// meek-compositor, creates an xdg_toplevel, commits dmabuf buffers
// via EGL, and meek-shell (running as the privileged client)
// should see it via meek_shell_v1.toplevel_added / toplevel_buffer.
//
// Not meek-shell code in any architectural sense -- it's a random
// third-party client we use to prove the pipeline. Lives in
// meek-shell/ purely because that's where the test scaffolding is.
//
// Deliberately minimal: one scene, no navigation, no gestures. Just
// enough to produce a steady dmabuf buffer stream the compositor
// can forward.
//

#include <stdlib.h>
#include <string.h>

#include "gui.h"
#include "gui_api.h"
#include "hot_reload.h"
#include "platform.h"
#include "scene.h"
#include "third_party/log.h"
#include "types.h"

//
// ===== UI handlers (wired by name from main.ui) ============================
//

//
// Popup-driven taps: each Settings row pops up an animated dialog
// instead of just logging. Used to exercise meek-ui's :appear /
// :disappear animator under Phase 2's render gate -- if the gate
// is correct, the spring/back-easing pop should play smoothly
// when invoked and the gate must keep the loop awake until the
// animation settles.
//
UI_HANDLER void on_popup_dismissed(gui_event *ev)
{
	log_info("[demo-settings] popup dismissed: confirmed=%d", ev->popup.confirmed ? 1 : 0);
}

UI_HANDLER void on_wifi_tap(gui_event *ev)
{
	(void)ev;
	log_info("[demo-settings] wifi tap");
	scene__popup_confirm("Connect to Wi-Fi network 'meek-test'?", "on_popup_dismissed");
}

UI_HANDLER void on_bluetooth_tap(gui_event *ev)
{
	(void)ev;
	log_info("[demo-settings] bluetooth tap");
	scene__popup_confirm("Turn on Bluetooth?", "on_popup_dismissed");
}

UI_HANDLER void on_airplane_tap(gui_event *ev)
{
	(void)ev;
	log_info("[demo-settings] airplane tap");
	scene__popup_confirm("Enable airplane mode? All radios will be turned off.", "on_popup_dismissed");
}

UI_HANDLER void on_display_tap(gui_event *ev)
{
	(void)ev;
	log_info("[demo-settings] display tap");
	scene__popup_ok("Display: 1080x2246 @ 60Hz, dark theme.", "on_popup_dismissed");
}

UI_HANDLER void on_sound_tap(gui_event *ev)
{
	(void)ev;
	log_info("[demo-settings] sound tap");
	scene__popup_ok("Master volume set to 60%.", "on_popup_dismissed");
}

UI_HANDLER void on_battery_tap(gui_event *ev)
{
	(void)ev;
	log_info("[demo-settings] battery tap");
	scene__popup_ok("Battery: 87%, charging via USB-C.", "on_popup_dismissed");
}

UI_HANDLER void on_about_tap(gui_event *ev)
{
	(void)ev;
	log_info("[demo-settings] about tap");
	scene__popup_ok("Poco F1 (beryllium) running postmarketOS edge.\nKernel 6.x, "
					"Mesa 24.0.9 (freedreno on Adreno 630).",
		"on_popup_dismissed");
}

//
// ===== main ================================================================
//

int main(int argc, char **argv)
{
	(void)argc;
	(void)argv;

	gui_app_config cfg;
	cfg.title = L"Settings";
	cfg.width = 720;
	cfg.height = 1280;
	cfg.clear_color = scene__hex(0x0f0f12);

	if (!platform__init(&cfg))
	{
		log_error("[demo-settings] platform__init failed");
		return 1;
	}

	//
	// Load UI + style from the build-time-known assets dir.
	// DEMO_SOURCE_DIR is a #define generated by build.sh.
	//
	if (!hot_reload__watch_style(DEMO_SOURCE_DIR "/main.style"))
	{
		log_error("[demo-settings] hot_reload__watch_style failed");
		platform__shutdown();
		return 1;
	}
	if (!hot_reload__watch_ui(DEMO_SOURCE_DIR "/main.ui"))
	{
		log_error("[demo-settings] hot_reload__watch_ui failed");
		platform__shutdown();
		return 1;
	}

	while (platform__tick())
	{
		hot_reload__tick();
	}

	hot_reload__shutdown();
	platform__shutdown();
	log_info("[demo-settings] exited cleanly");
	return 0;
}
